COMMENT = "Run 17"
LOG_DIR = "logs/cifar/17/"

RANDOM_SEED = 42

BATCH_SIZE = 1024
NUM_EPOCHS = 500

SCHEDULER = 1
PCT_START = 0.1
DIV_FACTOR = 100
FINAL_DIV_FACTOR = 1.0

BETA_1 = 0.90
BETA_2 = 0.95
WEIGHT_DECAY = 0.05
LEARNING_RATE = 1.5e-4

SAVE_MODELS = 1

# -----> ViTMAE Model<-----
IMAGE_SIZE = 32
PATCH_SIZE = 2
NUM_CHANNELS = 3
MASK_RATIO = 0.75

HIDDEN_SIZE = 128
INTERMEDIATE_SIZE = 256
NUM_HIDDEN_LAYERS = 6
NUM_ATTENTION_HEADS = 4

HIDDEN_DROPOUT_PROB = 0.0
ATTENTION_PROBS_DROPOUT_PROB = 0.0

DECODER_HIDDEN_SIZE = 64
DECODER_INTERMEDIATE_SIZE = 128
DECODER_NUM_HIDDEN_LAYERS = 2
DECODER_NUM_ATTENTION_HEADS = 4


#DATASOURCE = "/Users/martin/Sites/datasets/third-party/pytorch-datasets"

# bumblebee.research.cs.dal.ca
DATASOURCE = "/home/hmgillis/datasets/third-party/pytorch-datasets"
